services:
  - type: web
    name: blog-management-backend
    env: node
    rootDir: ./
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      # Set the following in the Render dashboard after creation (do not commit secrets):
      # - key: MONGODB_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # - key: JWT_EXPIRE
      #   value: 7d
      # - key: JWT_COOKIE_EXPIRE
      #   value: "7"
      # - key: FRONTEND_URL
      #   value: https://your-frontend.vercel.app

